-- MySQL Script generated by MySQL Workbench
-- Sat 24 Jun 2017 06:36:44 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_order_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_order_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_order_service` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_order_service` ;

-- -----------------------------------------------------
-- Table `ulbora_order_service`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_order_service`.`orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT NOT NULL,
  `billing_address_id` BIGINT NULL,
  `order_date` DATE NOT NULL,
  `comment` VARCHAR(150) NULL,
  `client_id` BIGINT NOT NULL,
  `payment` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_order_service`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_order_service`.`order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product` BIGINT NOT NULL,
  `sku` VARCHAR(100) NOT NULL,
  `ordered_qty` INT NOT NULL,
  `cancel_qty` INT NOT NULL DEFAULT 0,
  `returned_qty` INT NOT NULL DEFAULT 0,
  `back_ordered_qty` INT NOT NULL DEFAULT 0,
  `retail_price` DECIMAL(15,2) NULL,
  `status` VARCHAR(75) NOT NULL,
  `order_type` VARCHAR(45) NULL,
  `comment` VARCHAR(150) NULL,
  `order_id` BIGINT NOT NULL,
  `client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_item_order_idx` (`order_id` ASC),
  CONSTRAINT `fk_item_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `ulbora_order_service`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_order_service`.`package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_order_service`.`package` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `shipped_date` DATE NOT NULL,
  `tracking` VARCHAR(500) NULL,
  `shipping_address_id` BIGINT NULL,
  `package_number` INT NULL,
  `shipping_cost` DECIMAL(9,2) NULL,
  `comment` VARCHAR(150) NULL,
  `order_id` BIGINT NOT NULL,
  `client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_package_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_package_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ulbora_order_service`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_order_service`.`package_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_order_service`.`package_items` (
  `order_item_id` BIGINT NOT NULL,
  `package_id` BIGINT NOT NULL,
  INDEX `fk_package_items_package1_idx` (`package_id` ASC),
  PRIMARY KEY (`package_id`, `order_item_id`),
  INDEX `fk_package_items_order_item1_idx` (`order_item_id` ASC),
  CONSTRAINT `fk_package_items_package1`
    FOREIGN KEY (`package_id`)
    REFERENCES `ulbora_order_service`.`package` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_package_items_order_item1`
    FOREIGN KEY (`order_item_id`)
    REFERENCES `ulbora_order_service`.`order_item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
